### ISSUE TITLE
Add debug feature for DIRECT_RW() in transaction

### ISSUE THREAD

**Issue by ldorau** [pmem/valgrind#15]
Feature request:
DIRECT_RW() in debug mode could check if the field referenced by it has already been added to the undo log (of course if the referenced object was created before the transaction).

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
