### ISSUE TITLE
Error summary line

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/valgrind#29]
Memcheck prints nice summary of all found errors:
==28720== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
It's easy to write scripts which parse this one line and eg decide whether test succeeds or not.

Pmemcheck does not print anything like that. Every type of error has its own line, so scripts built around pmemcheck must parse many type of messages. It's easy to miss rare/new errors.

Please add error summary line to pmemcheck output.

**Comment by plebioda** [comment]
Fixed in https://github.com/pmem/valgrind/pull/34.
