### ISSUE TITLE
Extreme slowness in reallocate+checksum tests

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/valgrind#30]
In NVML's obj_realloc test we have to disable integrity checks when running under pmemcheck, because test runs extremely slow otherwise.

| pmemcheck \ integrity checks | disabled | enabled |
| --- | --- | --- |
| disabled | 5s | 5s |
| enabled | 12s | **10min** |

https://github.com/pmem/nvml/tree/master/src/test/obj_realloc

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
