### ISSUE TITLE
pmemcheck is slower on DAX

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/valgrind#31]
NVML's test obj_realloc with pmemcheck runs much slower on DAX than on normal file system. This is unexpected - DAX should always be faster.

| pmemcheck\file system | non-pmem(ext4) | pmem(DAX) |
| --- | --- | --- |
| disabled | 4.6s | 0.14s |
| enabled | 12s | **65s** |

https://github.com/pmem/nvml/tree/master/src/test/obj_realloc

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
