### ISSUE TITLE
Pool offsets in addition to runtime addresses

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/valgrind#33]
For example, in "Overlapping regions" text pmemcheck prints runtime addresses:
"Address: 0x6423400      size: 262144    tx_id: 9"
but they are useless for offline debugging (for example with pmempool).

Please print pool offsets in addition to runtime addresses.

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
