### ISSUE TITLE
Log stores enabled by default

### ISSUE THREAD

**Issue by plebioda** [pmem/valgrind#35]
I think it would be better to enable logging stores by default. Currently adding --log-stores=yes to valgrind arguments does not turn on logging stores unless you have explicit VALGRIND_LOG_STORES macro in your code. I think it should be enabled by default and you can disable it explicitly in your code on demand.

**Comment by marcinslusarz** [comment]
Few months ago we changed how it all works and now it's enough to pass --log-stores=yes to enable logging. VALGRIND_LOG_STORES doesn't exist anymore. Closing.
