### ISSUE TITLE
Multithreaded transaction error

### ISSUE THREAD

**Issue by tomaszkapela** [pmem/valgrind#38]
If during a transaction, threads are spawned and they try to change persistent objects, this might lead to hard to debug issues. Users might wrongly assume, that these threads are also within the same transaction. This is especially true for the C++ bindings. Maybe some valgrind feature could help remedy this.

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
