### ISSUE TITLE
Store marked as DIRTY before performing the store.

### ISSUE THREAD

**Issue by plebioda** [pmem/valgrind#43]
Currently the store is marked as DIRTY before actually performing that store. For example if the memory is read-only we get an error from pmemcheck which claims a store has beed done but the store hasn't been done because there was a SEGV.

Ref: pmem/issues#456

**Comment by tomaszkapela** [comment]
Ok, a word of explanation from me, pmc_main.c:1479
```C
case Ist_Store: {
                IRExpr *data = st->Ist.Store.data;
                IRType type = typeOfIRExpr(tyenv, data);
                tl_assert(type != Ity_INVALID);
                add_event_dw(sbOut, st->Ist.Store.addr, sizeofIRType(type),
                        data);
                addStmtToIRSB(sbOut, st);
                break;
}
```
`add_event_dw` registeres the `Ist_Store` event to be analyzed by pmemcheck and `addStmtToIRSB` adds the actual store to be made after re-synthesizing the native code. So swapping these two statements should *fix* the **bug**. Having said that, I don't consider this a bug. A properly written application shouldn't segfault and if it does, analyzing the output of pmemcheck makes no sense. On contrary, as it is now, it might actually help determine what happened. BTW, memcheck performs a lot better when analyzing use of uninitialized/inaccessible memory, it was designed with that particular feature in mind. I'm removing the **bug** label for now.
