### ISSUE TITLE
pmemcheck appears to ignore some pmem stores

### ISSUE THREAD

**Issue by GBuella** [pmem/valgrind#44]
The following branch can used to reproduce an issue, which seems to be an issue with pmemcheck:
https://github.com/GBuella/pmemfile/tree/pmemcheck_trouble

See tha latest commit in the branch for details.
Run the tests of the repository to reproduce.

**Comment by tomaszkapela** [comment]
I tried to reproduce this issue, but as we say it in Poland *u mnie działa*. Pmemcheck proprely reports the out of transaction stores in the test *rw.sparse_files*. As far as I can tell this is not a bug. Please verify this again and close this issue or provide more info on how to reproduce this.

**Comment by tomaszkapela** [comment]
@GBuella can we close this?

**Comment by GBuella** [comment]
http://www.theblaze.com/wp-content/uploads/2012/01/obama-yes-we-can_04-nov-08.jpg
