### ISSUE TITLE
unable to compile valgrind for arm arago 

### ISSUE THREAD

**Issue by lakshmisivareddy** [pmem/valgrind#57]
hi 
i am using Ubuntu 14.04 with arm arago tool chain 
when i tried to compile valgrind i am getting error 
steps i followed 
1) ./configure CC=arm-arago-linux-gnueabi-gcc  --host=armv7-arago-linux-gnueabi --prefix=/opt/valgrind 
2) make 
3) sudo make install  

when i did  'sudo make install' i am getting below error

 /usr/bin/install -c -m 644  libvex-arm-linux.a libvexmultiarch-arm-linux.a '/opt/valgrind/lib/valgrind'
 ( cd '/opt/valgrind/lib/valgrind' && arm-arago-linux-gnueabi-ranlib libvex-arm-linux.a )
/bin/bash: line 5: arm-arago-linux-gnueabi-ranlib: command not found
make[4]: *** [install-pkglibLIBRARIES] Error 127

**Comment by marcinslusarz** [comment]
This repository is a home to Valgrind modification called pmemcheck and this modification doesn't support ARM (contributions are welcomed though).
Nonetheless the error you get seems unrelated to pmemcheck, so if you just want normal Valgrind I'd recommend reporting it to upstream Valgrind (see http://valgrind.org/support/bug_reports.html for details).

**Comment by lakshmisivareddy** [comment]
Hi @marcinslusarz thanks for the support
