### ISSUE TITLE
Unable  to compile valigrnd

### ISSUE THREAD

**Issue by rksgkp** [pmem/valgrind#65]
Hi All,

I am trying to compile valigrind for mips architecture but at configuration time gettting below error message. Could you plz help to come out from this issue.

I used below command to configure the valgrind for mips architecture.

./configure --host=mips64 LDFLAGS=-static CC=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc CXX=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-g++ --build=x86_64  --enable-tls --prefix=/home/rajesh/Valgrind/valgrind_bins/ --exec-prefix=/home/rajesh/Valgrind/valgrind_bins
  

rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$ ./configure --host=mips64 LDFLAGS=-static CC=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc CXX=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-g++ --build=x86_64  --enable-tls --prefix=/home/rajesh/Valgrind/valgrind_bins/ --exec-prefix=/home/rajesh/Valgrind/valgrind_bins
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips64-strip... no
checking for strip... strip
configure: WARNING: using cross tools not prefixed with host triplet
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether ln -s works... yes
checking for mips64-gcc... /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc accepts -g... yes
checking for /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc option to accept ISO C89... none needed
checking whether /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc... gcc3
checking how to run the C preprocessor... /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc -E
checking whether we are using the GNU C++ compiler... yes
checking whether /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-g++ accepts -g... yes
checking dependency style of /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-g++... gcc3
checking for mips64-ranlib... no
checking for ranlib... ranlib
checking for gcc-ranlib... /usr/bin/gcc-ranlib
checking for a sed that does not truncate output... /bin/sed
checking for ar... /usr/bin/ar
checking for gcc-ar... /usr/bin/gcc-ar
checking for perl... /usr/bin/perl
checking for gdb... /usr/bin/gdb
checking dependency style of /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc... gcc3
checking for diff -u... yes
checking for /opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc option to accept ISO C99... -std=gnu99
checking for a supported version of gcc... ok (4.7.0)
checking build system type... x86_64-pc-none
checking host system type... mips64-unknown-elf
checking for a supported CPU... ok (mips64)vance t
checking for a 64-bit only build... no
checking for a 32-bit only build... no
checking for a supported OS... no (elf)
configure: error: Valgrind is operating system specific. Sorry.
rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$

Thanks for supports.
Rajesh

**Comment by marcinslusarz** [comment]
This repository is a home to Valgrind modification called pmemcheck and this modification doesn't support MIPS.
The error you get is unrelated to pmemcheck, so if you just want normal Valgrind I'd recommend directing this question to valgrind-users mailing list (see http://valgrind.org/support/mailing_lists.html for details).

**Comment by rksgkp** [comment]
I am able do the configuration but while compiling(make), getting below error message.

config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

         Maximum build arch: mips64
         Primary build arch: mips64
       Secondary build arch: 
                   Build OS: linux
     Link Time Optimisation: no
       Primary build target: MIPS64_LINUX
     Secondary build target: 
           Platform variant: vanilla
      Primary -DVGPV string: -DVGPV_mips64_linux_vanilla=1
         Default supp files: exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp 

rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$ make
echo "# This is a generated file, composed of the following suppression rules:" > default.supp
echo "# " exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp  >> default.supp
cat exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp >> default.supp
./auxprogs/make_or_upd_vgversion_h .
make  all-recursive
make[1]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0'
Making all in include
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/include'
Making all in VEX
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make  all-am
make[3]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
Making all in coregrind
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
make  all-am
make[3]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc -std=gnu99 -march=mips64r2 -mabi=64 -O2 -finline-functions -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin     -march=mips64r2 -mabi=64 -O2 -finline-functions -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin       -o valgrind valgrind-launcher-linux.o valgrind-m_debuglog.o  
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-launcher-linux.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-launcher-linux.o
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-m_debuglog.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-m_debuglog.o
collect2: error: ld returned 1 exit status
Makefile:2804: recipe for target 'valgrind' failed
make[3]: *** [valgrind] Error 1
make[3]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:1901: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:835: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0'
Makefile:704: recipe for target 'all' failed
make: *** [all] Error 2
rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$ 
rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$


Can you plz help to come out from this situation.

Thanks,
Rajesh
