### ISSUE TITLE
Valgrind compilation issues

### ISSUE THREAD

**Issue by rksgkp** [pmem/valgrind#66]
I am able do the configuration but while compiling(make), getting below error message.

config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

     Maximum build arch: mips64
     Primary build arch: mips64
   Secondary build arch: 
               Build OS: linux
 Link Time Optimisation: no
   Primary build target: MIPS64_LINUX
 Secondary build target: 
       Platform variant: vanilla
  Primary -DVGPV string: -DVGPV_mips64_linux_vanilla=1
     Default supp files: exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp 
rajesh@rajesh-dt:/Valgrind/valgrind-3.14.0$ make
echo "# This is a generated file, composed of the following suppression rules:" > default.supp
echo "# " exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp >> default.supp
cat exp-sgcheck.supp xfree-3.supp xfree-4.supp glibc-2.X-drd.supp glibc-2.34567-NPTL-helgrind.supp glibc-2.X.supp >> default.supp
./auxprogs/make_or_upd_vgversion_h .
make all-recursive
make[1]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0'
Making all in include
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/include'
Making all in VEX
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make all-am
make[3]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/VEX'
Making all in coregrind
make[2]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
make all-am
make[3]: Entering directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc -std=gnu99 -march=mips64r2 -mabi=64 -O2 -finline-functions -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin -march=mips64r2 -mabi=64 -O2 -finline-functions -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wold-style-declaration -fno-stack-protector -fno-strict-aliasing -fno-builtin -o valgrind valgrind-launcher-linux.o valgrind-m_debuglog.o
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-launcher-linux.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-launcher-linux.o
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-m_debuglog.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-m_debuglog.o
collect2: error: ld returned 1 exit status
Makefile:2804: recipe for target 'valgrind' failed
make[3]: *** [valgrind] Error 1
make[3]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:1901: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:835: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0'
Makefile:704: recipe for target 'all' failed
make: *** [all] Error 2
rajesh@rajesh-dt:/Valgrind/valgrind-3.14.0$
rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$

Can you plz help to come out from this situation.

Thanks,
Rajesh

**Comment by rksgkp** [comment]
Could some one plz help on above issue ?

**Comment by marcinslusarz** [comment]
I already told you in #65 - this is NOT the place to get support for Valgrind on MIPS.
