### ISSUE TITLE
Getting error while compiling valgrind

### ISSUE THREAD

**Issue by rksgkp** [pmem/valgrind#67]

**Comment by rksgkp** [comment]
Hi All,

I were trying to compile valgrind using cavium toolchain 64 bit for mips architecture. I am using below configuration option to configure and while compilation getting below error. Could plz hel me to resolve this compilation issue.

./configure --host=mips64-linux-gnu CC=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-gcc CXX=/opt/CAVIUMsdk312/OCTEON-SDK/tools/bin/mips64-octeon-linux-gnu-g++ --prefix=/home/rajesh/Valgrind/valgrind_bins --exec-prefix=/home/rajesh/Valgrind/valgrind_bins --target=x86_64-linux-gnu



Error message while compiling:

/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-launcher-linux.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-launcher-linux.o
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: valgrind-m_debuglog.o: uses different e_flags (0x200) fields than previous modules (0x0)
/opt/CAVIUMsdk312/OCTEON-SDK/tools-gcc-4.7/bin/../lib/gcc/mips64-octeon-linux-gnu/4.7.0/../../../../mips64-octeon-linux-gnu/bin/ld: failed to merge target specific data of file valgrind-m_debuglog.o
collect2: error: ld returned 1 exit status
Makefile:2804: recipe for target 'valgrind' failed
make[3]: *** [valgrind] Error 1
make[3]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:1901: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0/coregrind'
Makefile:835: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rajesh/Valgrind/valgrind-3.14.0'
Makefile:704: recipe for target 'all' failed
make: *** [all] Error 2
rajesh@rajesh-dt:~/Valgrind/valgrind-3.14.0$ 


Thanks,
Rajesh

**Comment by marcinslusarz** [comment]
I already told you in #65 - this is NOT the place to get support for Valgrind on MIPS.
