### ISSUE TITLE
pmemcheck doesn't support --xml=yes

### ISSUE THREAD

**Issue by jolivier23** [pmem/valgrind#69]
xml output is useful for our Jenkins CI infrastructure as the plugin is able to read and display issues found.  It would be useful if pmemcheck could support this feature

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
