### ISSUE TITLE
pmemcheck flags an issue on statistics update that should probably be suppressed

### ISSUE THREAD

**Issue by jolivier23** [pmem/valgrind#70]
If the user enables statistics on libpmemobj using pmemobj_ctl_set, pmemcheck complains about stores without adding to transactions for the statistic updates.   If it's an issue, it should be fixed (though I don't think we'd want to rollback stats).   If it isn't an issue, valgrind shouldn't report it.   In our tests, it accounts for hitting the 10K limit on errors.

**Comment by marcinslusarz** [comment]
This is actually a bug in PMDK and the fix is already merged (pmem/pmdk#3545). It will be part of 1.5.1 and 1.6.

Thanks for reporting.
