### ISSUE TITLE
Feature request: Option to filter entries with same callstack

### ISSUE THREAD

**Issue by jolivier23** [pmem/valgrind#71]
I worked on a similar tool (Intel's Inspector) and we had a mechanism for ignoring issues we've seen before (e.g. same callstack).   Granted they are not exactly the same but I've found that pmemcheck can stop analysis after reporting 10K of the same issue and it makes it so I can't find new issues until old ones are fixed.   I suppose I could add a suppression if those work but it would be convenient if there were an option to avoid reporting the same stack many times.

**Comment by wlemkows** [comment]
As of the moment no new features are planned. Closing this issue for now.
For further reading, please take a look at our [blog post with more details](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
