### ISSUE TITLE
Valgrind 3.16.0 | RHEL8 issue

### ISSUE THREAD

**Issue by AbinayaSandhiyaM** [pmem/valgrind#86]
Hi,

We been trying to create valgrind - 3.16.0 as RPM for RHEL8 for our project purpose.

On the time of buiding kcachegrind-0.7.4 we could see an issue that KDE4 could not find, And we understand that RHEL8 provides KDE5.

Below are the issue we been facing.

+ cd /root/rpmbuild/BUILD/kcachegrind-0.7.4
+ cmake -DCMAKE_INSTALL_PREFIX=/opt/valgrind/x86_64/3.16.1-1 -DCMAKE_PREFIX_PATH=/opt/valgrind/x86_64/3.16.1-1 .
-- The C compiler identification is GNU 8.4.1
-- The CXX compiler identification is GNU 8.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake/Modules/FindKDE4.cmake:61 (message):
  ERROR: Could not find KDE4 kde4-config
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)

could you please let us confirm whether Valgrind 3.16.0 can work with RHEL8 or any suggestion to come out of the above issue.

Thanks,

Regards,
Abinaya

**Comment by pbalcer** [comment]
This is a repository for valgrind's fork with support for Persistent Memory and the pmemcheck tool. Your question looks to related to the upstream project, and so my suggestion is to instead use valgrind's mailing list: https://valgrind.org/support/mailing_lists.html
