### ISSUE TITLE
Wrong uninitialized value detection.

### ISSUE THREAD

**Issue by nosehad** [pmem/valgrind#91]
Valgrind produces an uninitialized value error, even tough the buffer is initialized using memset from libc. For compiling i use gcc (Debian 12.2.0-14) 12.2.0 and valgrind-3.20.0 with the arguments used in the attached debug.sh.
[valgrind_error.zip](https://github.com/pmem/valgrind/files/11929004/valgrind_error.zip)

**Comment by ldorau** [comment]
This repository is a home to Valgrind modification called pmemcheck and the error you got seems unrelated to pmemcheck, so I recommend reporting it to upstream Valgrind (see http://valgrind.org/support/bug_reports.html for details).
